#!/usr/bin/env python3
"""Generate an Ed25519 keypair for signing mqjs tasks.

Private key -> tools/task_signing_key.pem (gitignored, keep secret).
Public key  -> main/task_pubkey.h (committed; embedded in firmware).

Re-running needs --force and invalidates every already-flashed device.
"""
import os
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY = os.path.join(ROOT, "tools", "task_signing_key.pem")
HDR = os.path.join(ROOT, "main", "task_pubkey.h")

if os.path.exists(KEY) and "--force" not in sys.argv:
    sys.exit(f"{KEY} already exists; pass --force to overwrite "
             f"(this invalidates every flashed device).")

sk = Ed25519PrivateKey.generate()
with open(KEY, "wb") as f:
    f.write(sk.private_bytes(serialization.Encoding.PEM,
                             serialization.PrivateFormat.PKCS8,
                             serialization.NoEncryption()))
os.chmod(KEY, 0o600)

pub = sk.public_key().public_bytes(serialization.Encoding.Raw,
                                   serialization.PublicFormat.Raw)
arr = ", ".join(f"0x{b:02x}" for b in pub)
with open(HDR, "w") as f:
    f.write("#pragma once\n")
    f.write("/* Auto-generated by tools/mqjs_keygen.py. Public key; safe to commit. */\n")
    f.write(f"static const unsigned char MQJS_TASK_PUBKEY[32] = {{ {arr} }};\n")

print(f"wrote {KEY}\nwrote {HDR}")
