#!/usr/bin/env python3
"""
bb_vectors.py — regenerate bb_vectors.h, the fixed Ed25519 test vectors for
test_bb_sig.c.

term_bb_pull.h leaves the verifier abstract (a callback with
crypto_sign_open()'s exact contract), so ONE suite drives the responder with
the real thing: components/tweetnacl/tweetnacl.c, over real signatures. Those
signatures have to come from somewhere, and generating a keypair at test time
would make the suite non-deterministic and dependent on a python at run time.
So they are generated ONCE, here, from a FIXED seed and checked in.

The signing is a self-contained RFC 8032 Ed25519 reference implementation
(hashlib only, no PyNaCl, no `cryptography`) so this stays runnable on any
python3. It is slow (a second or so per signature) and does not need to be
fast: it runs when a vector is added, not when the tests run.

    python3 bb_vectors.py > bb_vectors.h

Nothing verifies these vectors here on purpose — test_bb_sig.c verifies them
with TweetNaCl, which is the only opinion that matters. If this generator were
wrong, that suite would fail loudly rather than passing vacuously.
"""

import hashlib
import sys

# --------------------------------------------------------------- Ed25519
q = 2 ** 255 - 19
ell = 2 ** 252 + 27742317777372353535851937790883648493


def _h(m):
    return hashlib.sha512(m).digest()


def _inv(x):
    return pow(x, q - 2, q)


d = -121665 * _inv(121666) % q
I = pow(2, (q - 1) // 4, q)


def _xrecover(y):
    xx = (y * y - 1) * _inv(d * y * y + 1)
    x = pow(xx, (q + 3) // 8, q)
    if (x * x - xx) % q != 0:
        x = (x * I) % q
    if x % 2 != 0:
        x = q - x
    return x


By = 4 * _inv(5) % q
B = (_xrecover(By) % q, By % q)


def _add(P, Q):
    x1, y1 = P
    x2, y2 = Q
    x3 = (x1 * y2 + x2 * y1) * _inv(1 + d * x1 * x2 * y1 * y2)
    y3 = (y1 * y2 + x1 * x2) * _inv(1 - d * x1 * x2 * y1 * y2)
    return (x3 % q, y3 % q)


def _mul(P, e):
    Q = (0, 1)
    while e > 0:
        if e & 1:
            Q = _add(Q, P)
        P = _add(P, P)
        e >>= 1
    return Q


def _encode_point(P):
    x, y = P
    b = bytearray(y.to_bytes(32, "little"))
    b[31] |= (x & 1) << 7
    return bytes(b)


def _secret_scalar(sk):
    h = _h(sk)
    a = int.from_bytes(h[:32], "little")
    a &= (1 << 254) - 8
    a |= 1 << 254
    return a, h[32:64]


def publickey(sk):
    a, _ = _secret_scalar(sk)
    return _encode_point(_mul(B, a))


def sign(sk, pk, m):
    a, prefix = _secret_scalar(sk)
    r = int.from_bytes(_h(prefix + m), "little") % ell
    R = _encode_point(_mul(B, r))
    k = int.from_bytes(_h(R + pk + m), "little") % ell
    S = (r + k * a) % ell
    return R + S.to_bytes(32, "little")


# --------------------------------------------------------------- the vectors
# A fixed, obviously-a-test seed. This is NOT tools/task_signing_key.pem: the
# suite proves the responder honours whatever its verify callback says, not
# that the firmware's trust root is this one.
SEED = bytes(range(32))

TOPIC = "esp32p4-mqjs/task/u7q3x9f2"

# name, message. Ordered as test_bb_sig.c uses them; every one is a WELL FORMED
# request, because this suite's subject is the signature step and not the
# parser (test_bb_parse.c owns that). ctr values are spread so the suite can
# walk the mark forwards.
CASES = [
    ("live", "bbpull1\nctr=1000\ntop=%s\nwhat=live\nfrom=0\n" % TOPIC),
    ("stats", "bbpull1\nctr=2000\ntop=%s\nwhat=stats\n" % TOPIC),
    ("lastboot", "bbpull1\nctr=3000\ntop=%s\nwhat=lastboot\nfrom=0\n" % TOPIC),
    ("older", "bbpull1\nctr=500\ntop=%s\nwhat=live\n" % TOPIC),
    ("wrongtopic", "bbpull1\nctr=4000\ntop=%s/other\nwhat=live\n" % TOPIC),
    ("resume", "bbpull1\nctr=5000\ntop=%s\nwhat=live\nfrom=2\n" % TOPIC),
    # CRLF and a blank line: the tolerances the header names.
    ("crlf", "bbpull1\r\nctr=6000\r\n\r\ntop=%s\r\nwhat=stats\r\n" % TOPIC),
]


def carr(name, data):
    out = ["static const unsigned char %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 12):
        row = ", ".join("0x%02x" % b for b in data[i:i + 12])
        out.append("    %s," % row)
    out.append("};")
    return "\n".join(out)


def main():
    pk = publickey(SEED)
    w = sys.stdout.write
    w("/*\n")
    w(" * bb_vectors.h — GENERATED by bb_vectors.py, do not edit by hand.\n")
    w(" *\n")
    w(" * Fixed Ed25519 keypair and signed request envelopes for test_bb_sig.c,\n")
    w(" * which verifies them with the real components/tweetnacl. Each envelope is\n")
    w(" * signature(64) || message, byte for byte the format term_bb_pull.h's Q1\n")
    w(" * documents and the format tools/mqjs_push.py already produces.\n")
    w(" *\n")
    w(" * Regenerate:  python3 bb_vectors.py > bb_vectors.h\n")
    w(" */\n")
    w("#ifndef TERM_BB_VECTORS_H\n#define TERM_BB_VECTORS_H\n\n")
    w('#define BBV_TOPIC "%s"\n\n' % TOPIC)
    w("/* The test keypair's public key (seed = bytes(range(32))). */\n")
    w(carr("bbv_pk", pk))
    w("\n\n")
    for name, msg in CASES:
        env = sign(SEED, pk, msg.encode()) + msg.encode()
        w("/* %s: %r */\n" % (name, msg))
        w(carr("bbv_" + name, env))
        w("\n\n")
    w("#endif /* TERM_BB_VECTORS_H */\n")


if __name__ == "__main__":
    main()
