/*
 * test_bb_sig.c — Q1, over real Ed25519.
 *
 * term_bb_pull.h keeps the verifier abstract on purpose ("The public key is the
 * callback's business — that is how this file stays free of TweetNaCl and how
 * the device keeps its ONE trust root"), so what the contract pins is the
 * CALLBACK's contract and the ORDER it is called in:
 *
 *   "Open an Ed25519 envelope. EXACTLY crypto_sign_open()'s contract, which is
 *    what the device passes: `sm`/`smlen` is signature||message, `m` receives
 *    the message and must have room for `smlen` bytes, `*mlen` receives its
 *    length, and 0 means verified."
 *
 * test_bb_gate.c already proves the ordering and that the responder parses the
 * VERIFIED bytes, using a fake. This suite closes the other half: the fake is
 * replaced by the real components/tweetnacl over REAL signatures, so the
 * device's actual composition — crypto_sign_open writing into the responder's
 * scratch, the message length coming back through `*mlen` — is exercised rather
 * than assumed. The signatures are fixed vectors (bb_vectors.h, regenerated by
 * bb_vectors.py from a constant seed): deterministic, no key generation at test
 * time, and a wrong generator fails the first case instead of passing vacuously.
 *
 * Q1 is then attacked one bit at a time: every single bit flipped anywhere in a
 * valid envelope — signature or message — must come back bad-signature with
 * nothing published and the counter untouched.
 */
#include "bb_util.h"
#include "fake_port.h"
#include "tweetnacl.h"
#include "bb_vectors.h"

/* The device's own composition: term_bb_verify_fn IS crypto_sign_open's
 * contract, so the glue is this one line. */
static int real_verify(void *ctx, unsigned char *m, unsigned long long *mlen,
                       const unsigned char *sm, unsigned long long smlen)
{
    (void)ctx;
    bb.verify_calls++;
    return crypto_sign_open(m, mlen, sm, smlen, bbv_pk);
}

/* The same, under a key that is one bit different: "one trust root" means an
 * envelope signed for somebody else does not open here. */
static int other_key_verify(void *ctx, unsigned char *m,
                            unsigned long long *mlen, const unsigned char *sm,
                            unsigned long long smlen)
{
    unsigned char pk[32];
    (void)ctx;
    bb.verify_calls++;
    memcpy(pk, bbv_pk, sizeof pk);
    pk[0] ^= 0x01u;
    return crypto_sign_open(m, mlen, sm, smlen, pk);
}

static term_bb_env_t real_env(void)
{
    term_bb_env_t e = bb_env();
    e.verify = real_verify;
    return e;
}

/* Serve a real envelope. */
static term_bb_err_t serve_v(const void *env, size_t len, term_bb_result_t *res)
{
    term_bb_env_t e = real_env();
    return term_bb_serve(&e, env, len, res);
}

/* Serve and expect a refusal, with the two side-effect checks every refusal
 * owes (nothing published, the mark unmoved). */
static void refuse_v(const char *what, const void *env, size_t len,
                     term_bb_err_t want)
{
    term_bb_result_t res;
    term_bb_err_t got;
    uint64_t before = bb.mark;
    unsigned chunks = bb.chunks;

    got = serve_v(env, len, &res);
    t_checks++;
    if (got != want) {
        t_head(__FILE__, __LINE__);
        printf("     case    : %s\n     expected: %s\n     actual  : %s\n",
               what, term_bb_err_str(want), term_bb_err_str(got));
    }
    t_checks++;
    if (bb.chunks != chunks || bb.mark != before || res.accepted) {
        t_head(__FILE__, __LINE__);
        printf("     case    : %s\n     refused, yet published %u chunk(s) and "
               "left the mark at %llu (was %llu)\n", what,
               bb.chunks - chunks, (unsigned long long)bb.mark,
               (unsigned long long)before);
    }
    CHK_TRUE(bb_scratch_intact());
}

/* ===================================================================== */
/* The vectors are real                                                  */
/* ===================================================================== */

static void case_the_vectors_verify(void)
{
    unsigned char m[TERM_BB_ENVELOPE_MAX];
    unsigned long long mlen = 0;

    t_case("bb_vectors.h really is signature(64) || message under bbv_pk");
    CHK_INT(crypto_sign_open(m, &mlen, bbv_live, sizeof bbv_live, bbv_pk), 0);
    CHK_INT(mlen, sizeof bbv_live - TERM_BB_SIG_LEN);
    m[mlen] = 0;
    CHK_STR((const char *)m,
            "bbpull1\nctr=1000\ntop=" BBV_TOPIC "\nwhat=live\nfrom=0\n");
    CHK_STR(BBV_TOPIC, BB_TOPIC);

    t_case("...and the envelope layout is the documented one");
    /* The message starts right after the 64-byte signature, in the clear. */
    CHK_INT(memcmp(bbv_live + TERM_BB_SIG_LEN, "bbpull1\n", 8), 0);
    CHK_TRUE(sizeof bbv_live > TERM_BB_SIG_LEN);
    CHK_TRUE(sizeof bbv_live <= TERM_BB_ENVELOPE_MAX);
}

/* ===================================================================== */
/* Accepted, in counter order                                            */
/* ===================================================================== */

static void case_signed_requests_are_served(void)
{
    term_bb_result_t res;

    t_case("a real signed request is served, and burns its counter");
    bb_reset();
    (void)bb_fill(6u, 40u, "sig");
    CHK_INT(serve_v(bbv_live, sizeof bbv_live, &res), TERM_BB_OK);
    CHK_TRUE(res.accepted);
    CHK_TRUE(res.req.ctr == 1000u);
    CHK_INT(res.req.what, TERM_BB_WHAT_LIVE);
    CHK_STR(res.req.topic, BB_TOPIC);
    CHK_TRUE(bb.mark == 1000u);
    CHK_TRUE(bb.chunks >= 1u);
    CHK_INT(bb.verify_calls, 1);
    CHK_TRUE(res.records >= 6u);
    (void)bb_check_reply(&res);

    t_case("the very same bytes, replayed, are inert (Q2)");
    refuse_v("a replayed envelope", bbv_live, sizeof bbv_live,
             TERM_BB_E_REPLAY);
    refuse_v("...and again", bbv_live, sizeof bbv_live, TERM_BB_E_REPLAY);

    t_case("a signed stats request at a higher counter is served");
    bb.chunks = 0;
    CHK_INT(serve_v(bbv_stats, sizeof bbv_stats, &res), TERM_BB_OK);
    CHK_TRUE(res.req.ctr == 2000u);
    CHK_INT(res.req.what, TERM_BB_WHAT_STATS);
    CHK_TRUE(bb.mark == 2000u);
    CHK_INT(res.chunks, 1);
    CHK_STR(bb_jstr(bb.chunk[0], "what"), "stats");

    t_case("a signed lastboot request is served (absent, on a host)");
    bb.chunks = 0;
    CHK_INT(serve_v(bbv_lastboot, sizeof bbv_lastboot, &res), TERM_BB_OK);
    CHK_TRUE(bb.mark == 3000u);
    CHK_TRUE(bb_has(bb.chunk[0], "\"src\":\"lastboot\""));
    CHK_TRUE(bb_has(bb.chunk[0], "\"ok\":0"));

    t_case("a signed request BELOW the mark is a replay, not a signature error");
    refuse_v("an older counter", bbv_older, sizeof bbv_older,
             TERM_BB_E_REPLAY);

    t_case("a signed request for another device's topic is refused (Q3)");
    refuse_v("another device's topic", bbv_wrongtopic, sizeof bbv_wrongtopic,
             TERM_BB_E_TOPIC);

    t_case("a signed resume carries its cursor through");
    bb.chunks = 0;
    CHK_INT(serve_v(bbv_resume, sizeof bbv_resume, &res), TERM_BB_OK);
    CHK_TRUE(res.req.ctr == 5000u);
    CHK_INT(res.req.from, 2);
    CHK_INT(bb_jint(bb.chunk[0], "from"), 2);
    CHK_TRUE(bb.mark == 5000u);

    t_case("the documented tolerances survive being SIGNED (CRLF, blank line)");
    /* The CRs are inside the signature, so this only passes if the parser
     * tolerates them in the verified bytes — not merely in a hand-built
     * string. */
    bb.chunks = 0;
    CHK_INT(serve_v(bbv_crlf, sizeof bbv_crlf, &res), TERM_BB_OK);
    CHK_TRUE(res.req.ctr == 6000u);
    CHK_INT(res.req.what, TERM_BB_WHAT_STATS);
    CHK_STR(res.req.topic, BB_TOPIC);
}

/* ===================================================================== */
/* Q1: nothing outside the signature is trusted                          */
/* ===================================================================== */

static void case_tampering(void)
{
    static unsigned char buf[sizeof bbv_live + 8u];
    term_bb_result_t res;
    size_t n = sizeof bbv_live;
    unsigned i;

    bb_reset();
    bb.mark = 0;

    t_case("a flipped signature bit is refused");
    memcpy(buf, bbv_live, n);
    buf[0] ^= 0x01u;
    refuse_v("bit 0 of the signature", buf, n, TERM_BB_E_SIG);
    memcpy(buf, bbv_live, n);
    buf[63] ^= 0x80u;
    refuse_v("the last bit of the signature", buf, n, TERM_BB_E_SIG);

    t_case("a message edited after signing is refused");
    memcpy(buf, bbv_live, n);
    {
        /* Raise the counter in the plaintext: the attacker's obvious move
         * against a monotonic-counter gate. */
        char *msg = (char *)buf + TERM_BB_SIG_LEN;
        char *p = strstr(msg, "ctr=1000");
        REQUIRE(p != NULL);
        p[7] = '9';
        refuse_v("an edited counter", buf, n, TERM_BB_E_SIG);
    }
    memcpy(buf, bbv_live, n);
    {
        char *msg = (char *)buf + TERM_BB_SIG_LEN;
        char *p = strstr(msg, "what=live");
        REQUIRE(p != NULL);
        memcpy(p + 5, "stat", 4);
        refuse_v("an edited `what`", buf, n, TERM_BB_E_SIG);
    }

    t_case("an unsigned payload is refused (no envelope at all)");
    {
        /* An unsigned request is read as signature||message whatever it says,
         * so its first 64 bytes are taken for a signature: a SHORT one cannot
         * even reach the verifier (bad-length), and a long one reaches it and
         * fails there. tools/bb_pull.py's --raw produces the second shape. */
        static char plain[256];
        size_t n = (size_t)sprintf(plain,
            "bbpull1\nctr=7000\ntop=" BB_TOPIC "\nwhat=live\n");
        refuse_v("a bare short message", plain, n, TERM_BB_E_SIZE);
        while (n < TERM_BB_SIG_LEN + 32u) plain[n++] = '\n';
        refuse_v("a bare message past the signature length", plain, n,
                 TERM_BB_E_SIG);
    }

    t_case("a truncated envelope is refused");
    refuse_v("5 bytes short", bbv_live, n - 5u, TERM_BB_E_SIG);
    refuse_v("1 byte short", bbv_live, n - 1u, TERM_BB_E_SIG);
    /* Below the signature it is a length problem, and the verifier is never
     * even called (term_bb_pull.h's step 2 before step 3). */
    {
        int calls = bb.verify_calls;
        refuse_v("just the signature", bbv_live, TERM_BB_SIG_LEN,
                 TERM_BB_E_SIZE);
        refuse_v("half a signature", bbv_live, TERM_BB_SIG_LEN / 2u,
                 TERM_BB_E_SIZE);
        CHK_INT(bb.verify_calls, calls);
    }

    t_case("a signature lifted from another message does not fit this one");
    memcpy(buf, bbv_stats, TERM_BB_SIG_LEN);
    memcpy(buf + TERM_BB_SIG_LEN, bbv_live + TERM_BB_SIG_LEN,
           n - TERM_BB_SIG_LEN);
    refuse_v("a transplanted signature", buf, n, TERM_BB_E_SIG);

    t_case("a valid envelope under a different key is refused (one trust root)");
    {
        term_bb_env_t e = bb_env();
        e.verify = other_key_verify;
        CHK_INT(term_bb_serve(&e, bbv_live, n, &res), TERM_BB_E_SIG);
        CHK_INT(bb.chunks, 0);
        CHK_TRUE(bb.mark == 0u);
    }

    t_case("EVERY single-bit change anywhere in the envelope is refused");
    /* 129 bytes x 8 bits. Signature bytes and message bytes alike: the message
     * is inside the signed span, which is the whole of Q1. */
    for (i = 0; i < n; i++) {
        unsigned b;
        for (b = 0; b < 8u; b++) {
            term_bb_err_t got;
            memcpy(buf, bbv_live, n);
            buf[i] ^= (unsigned char)(1u << b);
            got = serve_v(buf, n, &res);
            t_checks++;
            if (got != TERM_BB_E_SIG) {
                t_head(__FILE__, __LINE__);
                printf("     flipping bit %u of byte %u gave %s, not "
                       "bad-signature\n", b, i, term_bb_err_str(got));
            }
        }
    }
    CHK_INT(bb.chunks, 0);
    CHK_TRUE(bb.mark == 0u);
    CHK_INT(bb.store_calls, 0);
    CHK_TRUE(bb_scratch_intact());

    t_case("...and the untouched envelope still opens afterwards");
    CHK_INT(serve_v(bbv_live, n, &res), TERM_BB_OK);
    CHK_TRUE(bb.mark == 1000u);
}

/* ===================================================================== */
/* The scratch really does have to hold the whole envelope                */
/* ===================================================================== */

static void case_scratch_holds_the_envelope(void)
{
    term_bb_result_t res;
    term_bb_env_t e;

    t_case("crypto_sign_open writes the message into the caller's scratch");
    /* "`m` receives the message and must have room for `smlen` bytes" — which
     * is why TERM_BB_SCRATCH_MIN is TERM_BB_ENVELOPE_MAX + 128 and not less.
     * At the floor, a maximum-size envelope must still verify. */
    bb_reset();
    bb_scratch(TERM_BB_SCRATCH_MIN);
    bb.mark = 0;
    e = real_env();
    CHK_INT(term_bb_serve(&e, bbv_stats, sizeof bbv_stats, &res), TERM_BB_OK);
    CHK_TRUE(bb.mark == 2000u);
    CHK_TRUE(bb_scratch_intact());
    CHK_TRUE(bb.max_chunk < TERM_BB_SCRATCH_MIN);
}

int main(void)
{
    t_suite("bb_sig");
    t_case("the port installs and the ring boots");
    fp_reset();
    CHK_TRUE(term_port_install(fp_port()));
    term_lp_ring_boot();
    CHK_TRUE(term_lp_ring_ready());

    case_the_vectors_verify();
    case_signed_requests_are_served();
    case_tampering();
    case_scratch_holds_the_envelope();

    fp_reclaim_all();
    return t_summary();
}
